### ISSUE TITLE
打包ios时报错

### ISSUE THREAD

**Issue by duanxianze** [flutter-food/gesture_recognition#1]
fatal error: 'gesture_recognition/GestureRecognitionPlugin.h'
    file not found
    #import <gesture_recognition/GestureRecognitionPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

version: "1.0.1"

flutter 1.9.1

**Comment by mochixuan** [comment]
我没有打过Flutter正式包。如果开发没有问题。打包应该不会出问题，你可以重新引用试试。
